[package]
name = "rust-core"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
zip = { workspace = true }
flate2 = { workspace = true }
image = { workspace = true }
quick-xml = { workspace = true }
libloading = { workspace = true, optional = true }
clap = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }
thiserror = { workspace = true }
dirs = { workspace = true }
rayon = { workspace = true }
regex = "1"
anyhow = { workspace = true }
serde = { version = "1", features = ["derive"] }
crossbeam-channel = "0.5"
base64 = { workspace = true }
webp = { workspace = true }

[dev-dependencies]
image = { workspace = true }
proptest = "1"

[features]
default = []
cbr = ["libloading"]
cli = ["clap", "tracing-subscriber"]
gui = ["tokio"]
